
language: objective-c
osx_image: xcode10.2 # new in https://docs.travis-ci.com/user/reference/osx/
sudo: true

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

notifications:
  email: false

addons:
  homebrew:
    packages:
    - curl # Fix the codecov upload issue

cache: cocoapods
podfile: MKAppDemo/Podfile

before_install:
    - env
    - locale
    - gem install cocoapods --prerelease --no-document --quiet
    - gem install xcpretty --no-document --quiet
    - pod --version
    - pod repo update --silent
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
    - set -o pipefail
    - echo Build the Demo apps
    - pod install --project-directory=MKAppDemo
    - cd MKAppDemo
    - xcodebuild build -workspace MKApp.xcworkspace -scheme 'MKApp' -configuration Debug -destination 'name=iPhone XS' | xcpretty -c
    - xcodebuild build -workspace MKApp.xcworkspace -scheme 'MKApp' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty -c
    - echo Clean DerivedData
    - rm -rf ~/Library/Developer/Xcode/DerivedData/
    - mkdir DerivedData

after_success:
  - bash <(curl -s https://codecov.io/bash)
