language: objective-c
osx_image: xcode10
cache: cocoapods
podfile: MKAppDemo/Podfile

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - XCODE_WORKSPACE=MKAppDemo/MKApp.xcworkspace
  matrix:
    - SCHEME="MKApp"

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
	# 如果依赖其他库,加上
  - pod repo update
  - pod install --project-directory=Example

script:
  - set -o pipefail
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Debug clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - pod lib lint --allow-warnings

after_success:
  - sleep 3

after_failure:
 - cat -n ~/Library/Logs/scan/*